# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        flysystem_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_articles_filesystem
                root_url: "%env(SITE_URL)%%articles_uploads_url%"
                cache_prefix: media/cache
                visibility: public

    cache: flysystem_resolver

    loaders:
        articles_flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_articles_filesystem
    data_loader: articles_flysystem_loader

    filter_sets:
        cache: ~

        articles_preview:
            quality: 75
            filters:
                fixed: { width: 480, height: 300 }
        articles_detail:
            quality: 90
            filters:
                fixed: { width: 750, height: 500 }