twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_4_layout.html.twig
        - form/my_theme.html.twig
    paths:
        'assets/images': images
        'assets/css': css

when@test:
    twig:
        strict_variables: true
